export const ERROR_CODES = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NO_PROCESS: "NO_PROCESS",
  PROCESS_ALREADY_EXISTS: "PROCESS_ALREADY_EXISTS",
  PROCESS_ALREADY_RUNNING: "PROCESS_ALREADY_RUNNING",
  PROCESS_ALREADY_PAUSED: "PROCESS_ALREADY_PAUSED",
  INVALID_INPUT: "INVALID_INPUT",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;
