export const ERROR_CODES = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NO_PROCESS: "NO_PROCESS",
  INVALID_PROCESS_ACTION: "INVALID_PROCESS_ACTION",
  INVALID_INPUT: "INVALID_INPUT",
  UNAUTHORIZED: "UNAUTHORIZED",
} as const;
